name: Lighthouse CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Create the lhci-report folder to store the Lighthouse report
      - name: Create lhci-report folder
        run: mkdir -p lhci-report

      # Run Lighthouse CI to generate the report
      - name: Run Lighthouse CI
        run: npx lhci autorun --output-path=lhci-report

      # Check the contents of the lhci-report folder
      - name: List lhci-report folder contents
        run: ls -la lhci-report

      # Update README with Lighthouse scores
      - name: Update README with Lighthouse scores
        run: node update-readme.js

      # Commit and push the updated README
      - name: Commit updated README
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update Lighthouse scores"
          git push
